import SingleProduct from '@/Components/SingleProduct/SingleProduct';
import style from '@/styles/products.module.css';
import Head from 'next/head';
import axios from 'axios';
import { GetServerSideProps } from 'next';

type Product = {
  no: number;
  name: string;
  images: Images[];
  stocks: string;
  price: number;
  _id:string;
};
type Images = {
    imageurl: string;
}

type ProductsProps = {
  data: Product[];
};

const Products: React.FC<ProductsProps> = ({ data }) => {
  return (
    <>
      <Head>
        <title>Seller Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={style.container}>
        <div className={style.headContainer}>
          <span className={style.no}>No.</span>
          <span className={style.image}>Product Image</span>
          <span className={style.name}>Product Name</span>
          <span className={style.stock}>Stock</span>
          <span className={style.price}>Price</span>
          <span className={style.more}>More</span>
        </div>

        {data.map((product, key) => (
          <SingleProduct data={product} no={key+1} key={key} />
        ))}
      </div>
    </>
  );
};

export default Products;

export const getServerSideProps: GetServerSideProps = async () => {
  const { data } = await axios.get(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/product/getproducts`);

  return {
    props: {
      data: data.products,
    },
  };
};
